import { MakeUp } from './MakeUp.js';
const makeUpData = [
    //Default
    new MakeUp('Default Lips', 'Lips', 'LipNormalDefault'), 
    new MakeUp('Default Eyebrows', 'Eyebrows', 'EyebrowNormalDefault'), 
    new MakeUp('Default Eyelashes', 'Eyelashes', 'EyelashesNormalDefault'),
    // Blush Data
    new MakeUp('Blush 1', 'Blush', 'blushanime', 'button1', 'blushanimeIcon'),
    new MakeUp('Blush 2', 'Blush', 'blushfever', 'button1', 'blushfeverIcon'),
    new MakeUp('Blush 3', 'Blush', 'blushfrackles', 'button1', 'blushfracklesIcon'),
    new MakeUp('Blush 4', 'Blush', 'blushlove', 'button1', 'blushloveIcon'),
    new MakeUp('Blush 5', 'Blush', 'blushorange', 'button1', 'blushorangeIcon'),
    new MakeUp('Blush 6', 'Blush', 'blushpink', 'button1', 'blushpinkIcon'),
    new MakeUp('Blush 7', 'Blush', 'blushnose', 'button1', 'blushnoseIcon'),
    new MakeUp('Blush 8', 'Blush', 'blushround', 'button1', 'blushroundIcon'),

    // Eyebrows Data
    new MakeUp('Eyebrows 1', 'Eyebrows', 'eyebrownormal1', 'button1', 'eyebrow1Icon'),
    new MakeUp('Eyebrows 2', 'Eyebrows', 'eyebrownormal2', 'button1', 'eyebrow2Icon'),
    new MakeUp('Eyebrows 3', 'Eyebrows', 'eyebrownormal3', 'button1', 'eyebrow3Icon'),
    new MakeUp('Eyebrows 4', 'Eyebrows', 'eyebrownormal4', 'button1', 'eyebrow4Icon'),
    new MakeUp('Eyebrows 5', 'Eyebrows', 'eyebrownormal5', 'button1', 'eyebrow5Icon'),

    // Eyelashes Data
    new MakeUp('Eyelashes1', 'Eyelashes', 'eyelashesnormal1', 'button1', 'eyelashes1Icon'),
    new MakeUp('Eyelashes2', 'Eyelashes', 'eyelashesnormal2', 'button1', 'eyelashes2Icon'),
    new MakeUp('Eyelashes3', 'Eyelashes', 'eyelashesnormal3', 'button1', 'eyelashes3Icon'),
    new MakeUp('Eyelashes4', 'Eyelashes', 'eyelashesnormal4', 'button1', 'eyelashes4Icon'),
    new MakeUp('Eyelashes5', 'Eyelashes', 'eyelashesnormal5', 'button1', 'eyelashes5Icon'),


    new MakeUp('Eyeliner1', 'Eyeliner', 'eyelinernormal1', 'button1', 'eyeliner1Icon'),
    new MakeUp('Eyeliner2', 'Eyeliner', 'eyelinernormal2', 'button1', 'eyeliner2Icon'),
    new MakeUp('Eyeliner3', 'Eyeliner', 'eyelinernormal3', 'button1', 'eyeliner3Icon'),
    new MakeUp('Eyeliner4', 'Eyeliner', 'eyelinernormal4', 'button1', 'eyeliner4Icon'),
    new MakeUp('Eyeliner5', 'Eyeliner', 'eyelinernormal5', 'button1', 'eyeliner5Icon'),
    // Eyeshadow Data
    new MakeUp('EyeShadowBrown', 'Eyeshadow', 'eyeshadownormalbrown', 'button1', 'eyeshadowbrownIcon'),
    new MakeUp('EyeShadowDragon', 'Eyeshadow', 'eyeshadownormaldragon', 'button1', 'eyeshadowdragonIcon'),
    new MakeUp('EyeShadowFairy', 'Eyeshadow', 'eyeshadownormalfairy', 'button1', 'eyeshadowfairyIcon'),
    new MakeUp('EyeShadowGold', 'Eyeshadow', 'eyeshadownormalgold', 'button1', 'eyeshadowgoldIcon'),
    new MakeUp('EyeShadowGreen', 'Eyeshadow', 'eyeshadownormalgreen', 'button1', 'eyeshadowgreenIcon'),
    new MakeUp('EyeShadowOrange', 'Eyeshadow', 'eyeshadownormalorange', 'button1', 'eyeshadoworangeIcon'),
    new MakeUp('EyeShadowPeach', 'Eyeshadow', 'eyeshadownormalpeach', 'button1', 'eyeshadowpeachIcon'),
    new MakeUp('EyeShadowPink', 'Eyeshadow', 'eyeshadownormalpink', 'button1', 'eyeshadowpinkIcon'),
    new MakeUp('EyeShadowPurple', 'Eyeshadow', 'eyeshadownormalpurple', 'button1', 'eyeshadowpurpleIcon'),

    // Lips Data
    new MakeUp('LipsBrown', 'Lips', 'lipnormalbrown', 'button1', 'lipsbrownIcon'),
    new MakeUp('LipsCherry', 'Lips', 'lipnormalcherry', 'button1', 'lipspinkIcon'),
    new MakeUp('LipsOrange', 'Lips', 'lipnormalorange', 'button1', 'lipsredIcon'),
    new MakeUp('LipsPink', 'Lips', 'lipnormalpink', 'button1', 'lipswineIcon'),
    new MakeUp('LipsRed', 'Lips', 'lipnormalred', 'button1', 'lipscherryIcon'),
    new MakeUp('LipsWine', 'Lips', 'lipnormalwine', 'button1', 'lipsorangeIcon'),

    // Pupil Data
    new MakeUp('PupilBlue', 'Pupil', 'PupilNormalBlue', 'button1', 'pupilblueIcon'),
    new MakeUp('PupilBlack', 'Pupil', 'pupilnormalblack', 'button1', 'pupilblackIcon'),
    new MakeUp('PupilDragon', 'Pupil', 'pupilnormaldragon', 'button1', 'pupildragonIcon'),
    new MakeUp('PupilFairy', 'Pupil', 'pupilnormalfairy', 'button1', 'pupilfairyIcon'),
    new MakeUp('PupilGreen', 'Pupil', 'pupilnormalgreen', 'button1', 'pupilgreenIcon'),
    new MakeUp('PupilMagical', 'Pupil', 'pupilnormalmagical', 'button1', 'pupilmagicIcon'),
    new MakeUp('PupilPink', 'Pupil', 'pupilnormalpink', 'button1', 'pupilpinkIcon'),
    new MakeUp('PupilRed', 'Pupil', 'pupilnormalred', 'button1', 'pupilredIcon'),
    new MakeUp('PupilYellow', 'Pupil', 'pupilnormalyellow', 'button1', 'pupilyellowIcon'),

    // Sticker Data
    new MakeUp('StickerBlushPink', 'Sticker', 'stickerblushpink', 'button1', 'stickerblushpinkIcon'),
    new MakeUp('StickerBlushPurple', 'Sticker', 'stickerblushpurple', 'button1', 'stickerblushpurpleIcon'),
    new MakeUp('StickerBlushRed', 'Sticker', 'stickerblushred', 'button1', 'stickerblushredIcon'),
    new MakeUp('StickerBlushYellow', 'Sticker', 'stickerblushyellow', 'button1', 'stickerblushyellowIcon'),
    new MakeUp('StickerDiamond', 'Sticker', 'stickerdiamond', 'button1', 'stickerdiamondIcon'),
    new MakeUp('StickerLove', 'Sticker', 'stickerlove', 'button1', 'stickerloveIcon'),
    new MakeUp('StickermoonlightcrownBlue', 'Sticker', 'stickermoonlightcrownblue', 'button1', 'stickermoonlightcrownblueIcon'),
    new MakeUp('StickermoonlightcrownPurple', 'Sticker', 'stickermoonlightcrownpurple', 'button1', 'stickermoonlightcrownpurpleIcon'),
    new MakeUp('StickermoonlightcrownRed', 'Sticker', 'stickermoonlightcrownred', 'button1', 'stickermoonlightcrownredIcon'),
    new MakeUp('StickermoonlightcrownWhite', 'Sticker', 'stickermoonlightcrownwhite', 'button1', 'stickermoonlightcrownwhiteIcon'),
    new MakeUp('StickermoonlightcrownYellow', 'Sticker', 'stickermoonlightcrownyellow', 'button1', 'stickermoonlightcrownyellowIcon'),
    new MakeUp('StickerprincessTears', 'Sticker', 'stickerprincesstears', 'button1', 'stickerprincesstearsIcon'),
    new MakeUp('StickerstarBlue', 'Sticker', 'stickerstarblue', 'button1', 'stickerstarblueIcon'),
    new MakeUp('StickerstarPink', 'Sticker', 'stickerstarpink', 'button1', 'stickerstarpinkIcon'),
    new MakeUp('StickerstarPurple', 'Sticker', 'stickerstarpurple', 'button1', 'stickerstarpurpleIcon'),
    new MakeUp('StickerstarRed', 'Sticker', 'stickerstarred', 'button1', 'stickerstarredIcon'),
    new MakeUp('StickerstarYellow', 'Sticker', 'stickerstaryellow', 'button1', 'stickerstaryellowIcons'),

    //hair data
     //new MakeUp('Default Black Hair', 'Hair', 'hair'),
     new MakeUp('01BlackB', 'Hair', '01blackB', 'button1', 'pupilyellowIcon'),
     new MakeUp('01BlondeB', 'Hair', '01blondeB', 'button1', 'pupilyellowIcon'),
     new MakeUp('01BlondeF', 'Hair', '01blondeF', 'button1', 'pupilyellowIcon'),
     new MakeUp('01BrownB', 'Hair', '01brownB', 'button1', 'pupilyellowIcon'),
     new MakeUp('01BrownF', 'Hair', '01brownF', 'button1', 'pupilyellowIcon'),
     new MakeUp('01PinkB', 'Hair', '01pinkB', 'button1', 'pupilyellowIcon'),
     new MakeUp('01PinkF', 'Hair', '01pinkF', 'button1', 'pupilyellowIcon'),
     new MakeUp('02BlackB', 'Hair', '02blackB', 'button1', 'pupilyellowIcon'),
     new MakeUp('02BlackF', 'Hair', '02blackF', 'button1', 'pupilyellowIcon'),
     new MakeUp('02BlondeB', 'Hair', '02blondeB', 'button1', 'pupilyellowIcon'),
     new MakeUp('02BlondeF', 'Hair', '02blondeF', 'button1', 'pupilyellowIcon'),
     new MakeUp('02BrownB', 'Hair', '02brownB', 'button1', 'pupilyellowIcon'),
     new MakeUp('02BrownF', 'Hair', '02brownF', 'button1', 'pupilyellowIcon'),
     new MakeUp('02PinkB', 'Hair', '02pinkB', 'button1', 'pupilyellowIcon'),
     new MakeUp('02PinkF', 'Hair', '02pinkF', 'button1', 'pupilyellowIcon'),
     new MakeUp('03BlackB', 'Hair', '03blackB', 'button1', 'pupilyellowIcon'),
     new MakeUp('03BlackF', 'Hair', '03blackF', 'button1', 'pupilyellowIcon'),
     new MakeUp('03BlondeB', 'Hair', '03blondeB', 'button1', 'pupilyellowIcon'),
     new MakeUp('03BlondeF', 'Hair', '03blondeF', 'button1', 'pupilyellowIcon'),
     new MakeUp('03BrownB', 'Hair', '03brownB', 'button1', 'pupilyellowIcon'),
     new MakeUp('03BrownF', 'Hair', '03brownF', 'button1', 'pupilyellowIcon'),
     new MakeUp('03PinkB', 'Hair', '03pinkB', 'button1', 'pupilyellowIcon'),
     new MakeUp('03PinkF', 'Hair', '03pinkF', 'button1', 'pupilyellowIcon'),
     new MakeUp('04BlackB', 'Hair', '04blackB', 'button1', 'pupilyellowIcon'),
     new MakeUp('04BlackF', 'Hair', '04blackF', 'button1', 'pupilyellowIcon'),
     new MakeUp('04BlondeB', 'Hair', '04blondeB', 'button1', 'pupilyellowIcon'),
     new MakeUp('04BlondeF', 'Hair', '04blondeF', 'button1', 'pupilyellowIcon'),
     new MakeUp('04BrownB', 'Hair', '04brownB', 'button1', 'pupilyellowIcon'),
     new MakeUp('04BrownF', 'Hair', '04brownF', 'button1', 'pupilyellowIcon'),
     new MakeUp('04PinkB', 'Hair', '04pinkB', 'button1', 'pupilyellowIcon'),
     new MakeUp('04PinkF', 'Hair', '04pinkF', 'button1', 'pupilyellowIcon'),
     new MakeUp('05BlackB', 'Hair', '05blackB', 'button1', 'pupilyellowIcon'),
     new MakeUp('05BlackF', 'Hair', '05blackF', 'button1', 'pupilyellowIcon'),
     new MakeUp('05BlondeB', 'Hair', '05blondeB', 'button1', 'pupilyellowIcon'),
     new MakeUp('05BlondeF', 'Hair', '05blondeF', 'button1', 'pupilyellowIcon'),
     new MakeUp('05BrownB', 'Hair', '05brownB', 'button1', 'pupilyellowIcon'),
     new MakeUp('05BrownF', 'Hair', '05brownF', 'button1', 'pupilyellowIcon'),
     new MakeUp('05PinkB', 'Hair', '05pinkB', 'button1', 'pupilyellowIcon'),
     new MakeUp('05PinkF', 'Hair', '05pinkF', 'button1', 'pupilyellowIcon'),
     new MakeUp('06BlackB', 'Hair', '06blackB', 'button1', 'pupilyellowIcon'),
     new MakeUp('06BlackF', 'Hair', '06blackF', 'button1', 'pupilyellowIcon'),
     new MakeUp('06BlondeB', 'Hair', '06blondeB', 'button1', 'pupilyellowIcon'),
     new MakeUp('06BlondeF', 'Hair', '06blondeF', 'button1', 'pupilyellowIcon'),
     new MakeUp('06BrownB', 'Hair', '06brownB', 'button1', 'pupilyellowIcon'),
     new MakeUp('06BrownF', 'Hair', '06brownF', 'button1', 'pupilyellowIcon'),
     new MakeUp('06PinkB', 'Hair', '06pinkB', 'button1', 'pupilyellowIcon'),
     new MakeUp('06PinkF', 'Hair', '06pinkF', 'button1', 'pupilyellowIcon'),
     new MakeUp('07BlackB', 'Hair', '07blackB', 'button1', 'pupilyellowIcon'),
     new MakeUp('07BlackF', 'Hair', '07blackF', 'button1', 'pupilyellowIcon'),
     new MakeUp('07BlondeB', 'Hair', '07blondeB', 'button1', 'pupilyellowIcon'),
     new MakeUp('07BlondeF', 'Hair', '07blondeF', 'button1', 'pupilyellowIcon'),
     new MakeUp('07BrownB', 'Hair', '07brownB', 'button1', 'pupilyellowIcon'),
     new MakeUp('07BrownF', 'Hair', '07brownF', 'button1', 'pupilyellowIcon'),
     new MakeUp('07PinkB', 'Hair', '07pinkB', 'button1', 'pupilyellowIcon'),
     new MakeUp('07PinkF', 'Hair', '07pinkF', 'button1', 'pupilyellowIcon'),
     new MakeUp('08BlackB', 'Hair', '08blackB', 'button1', 'pupilyellowIcon'),
     new MakeUp('08BlackF', 'Hair', '08blackF', 'button1', 'pupilyellowIcon'),
     new MakeUp('08BlondeB', 'Hair', '08blondeB', 'button1', 'pupilyellowIcon'),
     new MakeUp('08BlondeF', 'Hair', '08blondeF', 'button1', 'pupilyellowIcon'),
     new MakeUp('08BrownB', 'Hair', '08brownB', 'button1', 'pupilyellowIcon'),
     new MakeUp('08BrownF', 'Hair', '08brownF', 'button1', 'pupilyellowIcon'),
     new MakeUp('08PinkB', 'Hair', '08pinkB', 'button1', 'pupilyellowIcon'),
     new MakeUp('08PinkF', 'Hair', '08pinkF', 'button1', 'pupilyellowIcon'),
     new MakeUp('09BlackB', 'Hair', '09blackB', 'button1', 'pupilyellowIcon'),
     new MakeUp('09BlackF', 'Hair', '09blackF', 'button1', 'pupilyellowIcon'),
     new MakeUp('09BlondeB', 'Hair', '09blondeB', 'button1', 'pupilyellowIcon'),
     new MakeUp('09BlondeF', 'Hair', '09blondeF', 'button1', 'pupilyellowIcon'),
     new MakeUp('09BrownB', 'Hair', '09brownB', 'button1', 'pupilyellowIcon'),
     new MakeUp('09BrownF', 'Hair', '09brownF', 'button1', 'pupilyellowIcon'),
     new MakeUp('09PinkB', 'Hair', '09pinkB', 'button1', 'pupilyellowIcon'),
     new MakeUp('09PinkF', 'Hair', '09pinkF', 'button1', 'pupilyellowIcon'),
     new MakeUp('10BlackB', 'Hair', '10blackB', 'button1', 'pupilyellowIcon'),
     new MakeUp('10BlackF', 'Hair', '10blackF', 'button1', 'pupilyellowIcon'),
     new MakeUp('10BlondeB', 'Hair', '10blondeB', 'button1', 'pupilyellowIcon'),
     new MakeUp('10BlondeF', 'Hair', '10blondeF', 'button1', 'pupilyellowIcon'),
     new MakeUp('10BrownB', 'Hair', '10brownB', 'button1', 'pupilyellowIcon'),
     new MakeUp('10BrownF', 'Hair', '10brownF', 'button1', 'pupilyellowIcon'),
     new MakeUp('10VioletB', 'Hair', '10violetB', 'button1', 'pupilyellowIcon'),
     new MakeUp('10VioletF', 'Hair', '10violetF', 'button1', 'pupilyellowIcon'),
     new MakeUp('11BlackB', 'Hair', '11blackB', 'button1', 'pupilyellowIcon'),
     new MakeUp('11BlackF', 'Hair', '11blackF', 'button1', 'pupilyellowIcon'),
     new MakeUp('11BlondeB', 'Hair', '11blondeB', 'button1', 'pupilyellowIcon'),
     new MakeUp('11BlondeF', 'Hair', '11blondeF', 'button1', 'pupilyellowIcon'),
     new MakeUp('11BrownB', 'Hair', '11brownB', 'button1', 'pupilyellowIcon'),
     new MakeUp('11BrownF', 'Hair', '11brownF', 'button1', 'pupilyellowIcon'),
     new MakeUp('11PinkB', 'Hair', '11pinkB', 'button1', 'pupilyellowIcon'),
     new MakeUp('11PinkF', 'Hair', '11pinkF', 'button1', 'pupilyellowIcon'),

    

]

export const defaultMakeUpSkins = {
    'Lips': 'LipNormalDefault',
    'Eyebrows': 'EyebrowNormalDefault',
    'Eyelashes': 'EyelashesNormalDefault',
    'Pupil': 'PupilNormalBlue',
    'Hair': "hair"
};

const MakeUpPositions = {
    Eyebrows: { x: 0, y: 0 },
    Eyelashes: { x: 0, y: 0 },
    Eyeliner: { x: 0, y: 0 },
    Eyeshadow: { x: 0, y: 0 },
    Lips: { x: 0, y: 0 },
    Pupil: { x: 0, y: 0 },
    Sticker: { x: 0, y: 0 },
    Blush: {x: 0, y: 0},
   
}

export { makeUpData, MakeUpPositions }